BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "user" (
	"id"	INTEGER NOT NULL,
	"name"	VARCHAR(40) NOT NULL,
	"username"	VARCHAR(80) NOT NULL,
	"email"	VARCHAR(120) NOT NULL,
	"password"	VARCHAR(180) NOT NULL,
	"profile"	VARCHAR(180) NOT NULL,
	UNIQUE("email"),
	UNIQUE("username"),
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "arvore" (
	"id"	INTEGER NOT NULL,
	"name"	VARCHAR(30) NOT NULL,
	"especie"	VARCHAR(100) NOT NULL,
	UNIQUE("name"),
	UNIQUE("especie"),
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "familia" (
	"id"	INTEGER NOT NULL,
	"name"	VARCHAR(30) NOT NULL,
	UNIQUE("name"),
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "addarvore" (
	"id"	INTEGER NOT NULL,
	"qtd"	INTEGER NOT NULL,
	"origem"	VARCHAR(80) NOT NULL,
	"praca_id"	INTEGER NOT NULL,
	"arvore_id"	INTEGER NOT NULL,
	"familia_id"	INTEGER NOT NULL,
	FOREIGN KEY("arvore_id") REFERENCES "arvore"("id"),
	FOREIGN KEY("familia_id") REFERENCES "familia"("id"),
	FOREIGN KEY("praca_id") REFERENCES "praca"("id"),
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "praca" (
	"id"	INTEGER NOT NULL,
	"name"	VARCHAR(30) NOT NULL,
	"end"	VARCHAR(100) NOT NULL,
	"desc"	VARCHAR(500) NOT NULL,
	"image_1"	VARCHAR(30) NOT NULL,
	"image_2"	VARCHAR(30) NOT NULL,
	"image_3"	VARCHAR(30) NOT NULL,
	UNIQUE("image_3"),
	UNIQUE("name"),
	UNIQUE("image_1"),
	UNIQUE("image_2"),
	PRIMARY KEY("id")
);
INSERT INTO "user" ("id","name","username","email","password","profile") VALUES (3,' PJI110-0001-MONTE ALTO-Grupo-001 ','Grupo-001','pji110montealto01@gmail.com','$2b$12$cceWD7BZCrBeXaUzZfrh.eB7rTNR2IiLqCOYSk8V8TywzgRIVobN.','profile.jpg');
INSERT INTO "arvore" ("id","name","especie") VALUES (1,'Falso chorão','Schinus molle L. '),
 (2,'Cajueiro','Anacardium occidentale L. '),
 (3,'Mangueira','Mangifera indica L. '),
 (4,'Aroeira pimenteira','Schinus terebinthifolia Raddi'),
 (5,'Peito de pombo','Tapirira guianensis Aubl'),
 (6,'Peroba ','Aspidosperma polyneuron Müll. Arg.'),
 (7,'Jasmin manga ','Plumeria rubra L. '),
 (8,'Cheflera ','Schefflera actinophylla Harms '),
 (9,'Carnaúba ','Copernicia prunifera Moore '),
 (10,'Palmito juçara','Euterpe edulis Mart.'),
 (11,'Palmeira leque','Licuala grandisH. Wendl. ex Linden '),
 (12,'Palmeira imperial ','Roystonea oleracea L.H. Bailey'),
 (13,'Espatódea ','Spathodea campanulata P. Beauv. '),
 (14,'Ypê rosa ','Tabebuia rosea'),
 (15,'Ypê amarelo','Tabebuia alba '),
 (16,'Ypê roxo ','Tabebuia impetiginosa'),
 (17,'Ypê mirim','Tecoma stans (L.) Juss. ex Kunth '),
 (18,'Oiti','Licania tomentosa (Benth.) Fritsch '),
 (19,'Marinheiro ','Licania kunthiana Hook. f.'),
 (20,'Chapéu de sol','Terminalia catappa L. '),
 (21,'Pau de sebo ','Sapium sebiferum (L.) Roxb.'),
 (22,'Pata de vaca ','Bauhinia forficata Link'),
 (23,'Pau Brasil','Caesalpinia echinata Lam.'),
 (24,'Pau ferro','Caesalpinia leiostachya Ducke'),
 (25,'Sibipiruna ','Caesalpinia pluviosa DC.'),
 (26,'Cássia rosa','Cassia grandis L. f.');
INSERT INTO "familia" ("id","name") VALUES (1,'Anacardiaceae'),
 (2,'Apocynaceae'),
 (3,'Araliaceae'),
 (4,'Arecaceae'),
 (5,'Bignoniaceae'),
 (6,'Chrysobalanaceae'),
 (7,'Combretaceae '),
 (8,'Euphorbiaceae '),
 (9,'Fabaceae'),
 (10,'Lauraceae'),
 (11,'Lecythidaceae'),
 (12,'Lythraceae'),
 (13,'Magnoliaceae'),
 (14,'Malpighiaceae'),
 (15,'Malvaceae'),
 (16,'Melastomataceae'),
 (17,'Moraceae'),
 (18,'Muntingiaceae'),
 (19,'Myrtaceae'),
 (20,'Nyctaginaceae'),
 (21,'Oleaceae'),
 (22,'Pinaceae'),
 (23,'Proteaceae'),
 (24,'Rhamnaceae'),
 (25,'Rosaceae'),
 (26,'Sapindaceae'),
 (27,'Solanaceae');
INSERT INTO "praca" ("id","name","end","desc","image_1","image_2","image_3") VALUES (1,'Praça São Cristóvão','Rua Gustavo de Godoy','','scristovao1.jpg','scristovao2.jpg','scristovao3.jpg'),
 (2,'Praça Dr. Raul da Rocha Medeiros/Praça da Bandeira','Rua Nhonhô do Livramento','','central1.jpg','central2.jpg','central3.jpg'),
 (3,'Praça ao lado da UBS Silvio Govoni','Avenida José Luis Franco da Rocha','','asiviogov1.jpg','asiviogov2.jpg','asiviogov3.jpg'),
 (4,'Praça São Benedito','Rua Nhonhô do Livramento','','sbenedito1.jpg','sbenedito2.jpg','sbenedito3.jpg'),
 (5,'Praça do Parquinho','Rua Carlos Kielander','','parquinho1.jpg','parquinho2.jpg','parquinho3.jpg'),
 (6,' Praça dos Peixes','Rua Marechal Deodoro da Fonseca','','peixes1.jpg','peixes2.jpg','peixes3.jpg'),
 (7,'Praça Jardim Alvorada','Campo de futebol','','alvocampo1.jpg','alvocampo2.jpg','alvocampo3.jpg'),
 (8,'1ª Praça do Jardim Bela Vista','Avenida Jorge Bahdur','','1bvista1.jpg','1bvista2.jpg','1bvista3.jpg'),
 (9,'1ª Praça Jardim Alvorada','Rua Horácio Barione Baby','','alvorada1.jpg','alvorada2.jpg','alvorada3.jpg'),
 (10,'Praça do trabalhador','Rua Umuarama','','trabalhador1.jpg','trabalhador2.jpg','trabalhador3.jpg'),
 (11,'Parque Cosmo','Avenida Cosmo Inforçatti','','cosmo1.jpg','cosmo2.jpg','cosmo3.jpg'),
 (12,' 2ª Praça do Jardim Bela Vista','Avenida Jorge Bahdur','','2bvista1.jpg','2bvista2.jpg','2bvista3.jpg'),
 (13,'Praça Jardim Esperança','Rua Roberto Lauer','','esperanca1.jpg','esperanca2.jpg','esperanca3.jpg');
COMMIT;
